export const GET_SONGS_START = "GET_SONGS_START";
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS";
export const GET_SONGS_FAILURE = "GET_SONGS_FAILURE";


export const POST_SONGS_START = "POST_SONGS_START";
export const POST_SONGS_SUCCESS = "POST_SONGS_SUCCESS";
export const POST_SONGS_FAILURE = "POST_SONGS_FAILURE";

export const GET_SPECIFIC_SONGS_START = "GET_SPECIFIC_SONGS_START";
export const GET_SPECIFIC_SONGS_SUCCESS = "GET_SPECIFIC_SONGS_SUCCESS";
export const GET_SPECIFIC_SONGS_FAILURE = "GET_SPECIFIC_SONGS_FAILURE";

export const PUT_SONGS_START = "PUT_SONGS_START";
export const PUT_SONGS_SUCCESS = "PUT_SONGS_SUCCESS";
export const PUT_SONGS_FAILURE = "PUT_SONGS_FAILURE";

export const DELETE_SONGS_START = "DELETE_SONGS_START";
export const DELETE_SONGS_SUCCESS = "DELETE_SONGS_SUCCESS";
export const DELETE_SONGS_FAILURE = "PUT_SONGS_FAILURE";

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_SPECIFIC_USER_START = "GET_SPECIFIC_USER_START";
export const GET_SPECIFIC_USER_SUCCESS = "GET_SPECIFIC_USER_SUCCESS";
export const GET_SPECIFIC_USER_FAILURE = "GET_SPECIFIC_USER_FAILURE";
